apiVersion: v1
kind: Pod
metadata:
  name: synthnet-drucker-se-su-st-st-256-100
spec:
  restartPolicy: Never
  containers:
  - name: synthnet-drucker-se-su-st-st-256-100
    image: beuthdritter/synthnet-render-pipeline
    volumeMounts:
            - name: output-volume
              mountPath: /workspace/out
    command:
      [
        "conda",
        "run",
        "-n",
        "py39-synthnet-render-pipeline",
        "bash",
        "scripts/runs_synthnet/900841-00.00.00_drucker_se_su_static_static_256_100.sh",
        "3",
        "42",
        "43"
      ]
    resources:
      requests:
        memory: "16Gi"
      limits:
        nvidia.com/gpu: 2
        memory: "64Gi"
  nodeSelector:
    gpu: v100
  volumes:
  - name: output-volume 
    persistentVolumeClaim:
      claimName: output-pvc
