apiVersion: v1
kind: Pod
metadata:
  name: synthnet-drucker-se-su-st-st-256-12
spec:
  restartPolicy: Never
  containers:
  - name: synthnet-drucker-se-su-st-st-256-12
    image: beuthdritter/synthnet-render-pipeline
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/gcp/synthnet-gcs.json
    volumeMounts:
            - name: output-volume
              mountPath: /workspace/out
            - name: synthnet-gcs-key-volume
              mountPath: /etc/gcp
              readOnly: true
    command:
      [
        "conda",
        "run",
        "-n",
        "py39-synthnet-render-pipeline",
        "bash",
        "scripts/runs_synthnet/900841-00.00.00_drucker_se_su_static_static_256_12.sh",
        "3",
        "42",
        "43"
      ]
    resources:
      requests:
        memory: "16Gi"
      limits:
        nvidia.com/gpu: 1
        memory: "64Gi"
  nodeSelector:
    gpu: v100
  volumes:
  - name: output-volume 
    persistentVolumeClaim:
      claimName: output-pvc
  - name: synthnet-gcs-key-volume
    secret:
      secretName: synthnet-gcs-key
