apiVersion: v1
kind: Pod
metadata:
  name: ilsvcr-sn18
spec:
  restartPolicy: Never
  containers:
  - name: render-ilsvcr-sn18
    image: registry.bht-berlin.de/iisy/synthnet/rendering-pipeline
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/gcp/synthnet-gcs.json
    volumeMounts:
            - name: output-volume
              mountPath: /workspace/out
            - name: shapenet-volume
              mountPath: /workspace/data
            - name: synthnet-gcs-key-volume
              mountPath: /etc/gcp
              readOnly: true
    command:
      [
        "conda",
        "run",
        "-n",
        "py39-synthnet-rendering-pipeline",
        "bash",
        "scripts/ilsvcr_sn18.sh",
        "3",
        "42",
        "43"
      ]
    resources:
      requests:
        memory: "8Gi"
      limits:
        nvidia.com/gpu: 1
        memory: "64Gi"
  imagePullSecrets:
  - name: private-registry-auth
  nodeSelector:
    gpu: v100
  volumes:
  - name: output-volume 
    persistentVolumeClaim:
      claimName: output-pvc
  - name: shapenet-volume 
    persistentVolumeClaim:
      claimName: shapenet-pvc
  - name: synthnet-gcs-key-volume
    secret:
      secretName: synthnet-gcs-key
