apiVersion: v1
kind: Pod
metadata:
  name: synthnet-7054-12-300-l-isogrid-su-st-st-512-32
spec:
  restartPolicy: Never
  containers:
  - name: synthnet-7054-12-300-l-isogrid-su-st-st-512-32
    image: beuthdritter/synthnet-render-pipeline
    env:
      - name: GIT_NAME
        valueFrom:
          secretKeyRef:
            name: git-creds
            key: username
            optional: false
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-creds
            key: token
            optional: false
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/gcp/synthnet-gcs.json
    volumeMounts:
            - name: synthnet-render-pipeline-volume
              mountPath: /workspace/data
            - name: output-volume
              mountPath: /workspace/out
            - name: src-volume
              mountPath: /src-pv
            - name: synthnet-gcs-key-volume
              mountPath: /etc/gcp
              readOnly: true
    command: ["/bin/bash", "-c"]
    args:
      # - while true; do sleep 30; done;
      - cd /src-pv/synthnet-render-pipeline;
        git checkout develop;
        git pull;
        cd /workspace;
        cp -r /src-pv/synthnet-render-pipeline/* /workspace;
        bash scripts/runs_synthnet/7054-12-300-L_drucker/7054-12-300-L_drucker_isogrid_su_st_st_512_32.sh 3 42 43;
    resources:
      requests:
        memory: "16Gi"
      limits:
        nvidia.com/gpu: 1
        memory: "64Gi"
  imagePullSecrets:
  - name: private-registry-auth
  nodeSelector:
    gpu: v100
  volumes:
  - name: synthnet-render-pipeline-volume
    persistentVolumeClaim:
      claimName: synthnet-render-pipeline-pvc
  - name: output-volume
    persistentVolumeClaim:
      claimName: output-pvc
  - name: src-volume
    persistentVolumeClaim:
      claimName: src-pvc
  - name: synthnet-gcs-key-volume
    secret:
      secretName: synthnet-gcs-key
